#!/usr/bin/env python3
"""Generate ATS2 stadef declarations for WCAG relative luminance.

Usage: python3 tools/gen_theme_lum.py > src/theme_lum.hats

WCAG 2.1 relative luminance formula:
  For each sRGB channel C (0-255):
    C_lin = C/255/12.92                  if C/255 <= 0.04045
    C_lin = ((C/255 + 0.055)/1.055)^2.4  otherwise
  L = 0.2126 * R_lin + 0.7152 * G_lin + 0.0722 * B_lin
  Scaled to 0-10000 integer (L * 10000).
"""

def srgb_to_linear(c):
    """Convert sRGB channel (0-255) to linear (0.0-1.0)."""
    c_norm = c / 255.0
    if c_norm <= 0.04045:
        return c_norm / 12.92
    return ((c_norm + 0.055) / 1.055) ** 2.4

def relative_luminance(r, g, b):
    """WCAG relative luminance, scaled to 0-10000."""
    r_lin = srgb_to_linear(r)
    g_lin = srgb_to_linear(g)
    b_lin = srgb_to_linear(b)
    L = 0.2126 * r_lin + 0.7152 * g_lin + 0.0722 * b_lin
    return round(L * 10000)

def hex_to_rgb(h):
    """Parse hex color to (r, g, b)."""
    h = h.lstrip('#')
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))

# Theme color definitions: (name, hex)
COLORS = {
    # Light theme
    'LIGHT_BG':         '#fafaf8',
    'LIGHT_FG':         '#2a2a2a',
    'LIGHT_ACCENT':     '#4a7c59',
    'LIGHT_CHROME_BG':  '#f5f0eb',
    'LIGHT_CHROME_FG':  '#3a3a3a',
    'LIGHT_LINK':       '#2a5f8f',
    'LIGHT_HIGHLIGHT':  '#fff3cd',
    'LIGHT_DIVIDER':    '#e0e0e0',
    # Dark theme (comfort-constrained: max 15:1 contrast)
    'DARK_BG':          '#222222',
    'DARK_FG':          '#939393',
    'DARK_ACCENT':      '#5a9068',
    'DARK_CHROME_BG':   '#2c2c2c',
    'DARK_CHROME_FG':   '#939393',
    'DARK_LINK':        '#6898b8',
    'DARK_HIGHLIGHT':   '#3a3520',
    'DARK_DIVIDER':     '#404040',
    # Sepia theme
    'SEPIA_BG':         '#f0e6d2',
    'SEPIA_FG':         '#3a3020',
    'SEPIA_ACCENT':     '#7a6040',
    'SEPIA_CHROME_BG':  '#e8dcc8',
    'SEPIA_CHROME_FG':  '#3a3020',
    'SEPIA_LINK':       '#5a4020',
    'SEPIA_HIGHLIGHT':  '#e8d8b0',
    'SEPIA_DIVIDER':    '#d0c0a0',
}

print('(* theme_lum.hats — auto-generated by tools/gen_theme_lum.py')
print(' * DO NOT EDIT — regenerate with: python3 tools/gen_theme_lum.py > src/theme_lum.hats')
print(' *')
print(' * WCAG relative luminance scaled to 0-10000. *)')
print()

for name, hexcolor in COLORS.items():
    r, g, b = hex_to_rgb(hexcolor)
    lum = relative_luminance(r, g, b)
    print(f'stadef {name}_LUM = {lum}  (* {hexcolor} R={r} G={g} B={b} *)')
    # Also emit RGB channel stadefs
    print(f'stadef {name}_R = {r}')
    print(f'stadef {name}_G = {g}')
    print(f'stadef {name}_B = {b}')
    # Emit hex value as integer for CSS generation
    print(f'stadef {name}_HEX = 0x{hexcolor.lstrip("#")}')
    print()

# Verify contrast ratios
print('(* ========== Contrast ratio verification ========== *)')
print('(* AA requires (L_hi + 50) * 10 >= 45 * (L_lo + 50) *)')
print()

pairs = [
    ('LIGHT_BG', 'LIGHT_FG', 'Light bg/fg'),
    ('LIGHT_CHROME_BG', 'LIGHT_CHROME_FG', 'Light chrome'),
    ('LIGHT_BG', 'LIGHT_LINK', 'Light bg/link'),
    ('DARK_FG', 'DARK_BG', 'Dark fg/bg'),
    ('DARK_CHROME_FG', 'DARK_CHROME_BG', 'Dark chrome'),
    ('DARK_LINK', 'DARK_BG', 'Dark link/bg'),
    ('SEPIA_BG', 'SEPIA_FG', 'Sepia bg/fg'),
    ('SEPIA_CHROME_BG', 'SEPIA_CHROME_FG', 'Sepia chrome'),
    ('SEPIA_BG', 'SEPIA_LINK', 'Sepia bg/link'),
]

for hi_name, lo_name, desc in pairs:
    hi_rgb = hex_to_rgb(COLORS[hi_name])
    lo_rgb = hex_to_rgb(COLORS[lo_name])
    hi_lum = relative_luminance(*hi_rgb)
    lo_lum = relative_luminance(*lo_rgb)
    # Ensure hi_lum > lo_lum
    if hi_lum < lo_lum:
        hi_lum, lo_lum = lo_lum, hi_lum
    ratio = (hi_lum + 50) / (lo_lum + 50)
    aa_ok = (hi_lum + 50) * 10 >= 45 * (lo_lum + 50)
    print(f'(* {desc}: {ratio:.1f}:1 {"PASS" if aa_ok else "FAIL"} AA *)')
